context:
  name: altair-aitools-devkit
  version: 1.0b5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://maven.rapidminer.com/repository/pypi-snapshot/packages/altair-aitools-devkit/${{ version }}/altair_aitools_devkit-${{ version }}.tar.gz
  sha256: d87c60f4e90e1927d1fabe3e771752c93ef3042f860f0c8bacc4d20fc9b21117

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - build-extension = altair_aitools.dev._builder:build_extension

requirements:
  host:
    - python ${{ python_min }}
    - hatchling
    - pip
  run:
  - python >=${{ python_min }}
  - networkx >=3.0,<4
  - pipdeptree >=2.20,<3
  - pyyaml >=6.0,<7
  - conda-index >=0.5.0,<0.6
  - libmambapy >=2.0,<3
  - altair-aitools-runtime >=1.0b5

tests:
  - python:
      imports:
        - altair_aitools.dev
  - requirements:
      run:
        - pip
    script:
      - pip check
      - build-extension --help

about:
  summary: altair-aitools-devkit is a comprehensive package that provides a set of tools to develop Altair RapidMiner AI tools extensions in Python
  license: AGPL-3.0-only
  license_file: LICENSE
  homepage: https://altair.com/altair-rapidminer

extra:
  recipe-maintainers:
    - skontar-altair
    - pczako-altair
